-- トランザクションテーブル
INSERT INTO T_TRANSACTION (ID, ITEM1, ITEM2, ITEM3)
VALUES ('1', 'A1 ', ' value2 ', ' value3 ');
INSERT INTO T_TRANSACTION (ID, ITEM1, ITEM2, ITEM3)
VALUES ('2', ' A4', ' value5 ', ' value6 ');
INSERT INTO T_TRANSACTION (ID, ITEM1, ITEM2, ITEM3)
VALUES ('3', 'B3 ', ' value8 ', ' value9 ');
-- グループマスタ
INSERT INTO T_GROUP_MASTER (ITEM1, GROUP_NAME)
VALUES ('A1', 'GROUP-A');
INSERT INTO T_GROUP_MASTER (ITEM1, GROUP_NAME)
VALUES ('A2', 'GROUP-A');
INSERT INTO T_GROUP_MASTER (ITEM1, GROUP_NAME)
VALUES ('B3', 'GROUP-B');
-- カラムフィルター
INSERT INTO T_COLUMNS_FILTER (COLUMN_NAME)
VALUES ('ID');
INSERT INTO T_COLUMNS_FILTER (COLUMN_NAME)
VALUES ('ITEM1');
INSERT INTO T_COLUMNS_FILTER (COLUMN_NAME)
VALUES ('GROUP');